name: Deploy

"on":
  release:
    types:
      - created


env:
  REGISTRY: ghcr.io


jobs:
  docker-pull-latest-image:

    runs-on: self-hosted
    # runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Clean docker artifacts
        run: |
          docker system prune -af

      - name: Deploy new version
        run: |
          echo "Apply new version with tag 'latest'"
          kubectl apply -f .k8s/deployment.yaml

