name: Testing

"on":
  push:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Generate simple env
      run: |
        cat > src/.env << EOF
          export SENTRY_DSN="https://xxxhsdshd@o444444.ingest.sentry.io/1234567"
          export TELEGRAM_BOT_TOKEN='1234567890:QWERTYUHGVFDRTGaaa'
          export VERSION=0.1.2
        EOF

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        make install-deps-dev

    - name: Run black
      run: |
        make black

    - name: Run isort
      run: |
        make isort

    - name: Run flake8
      run: |
        make flake8
